
class _Const(object):
    MAX_BATCH_ELEMENT_COUNT = 25
    COL_PER_ROW = 2048
    ROW_PER_FILE = 10000
    DB_NAME = "data_on_07_19"
    AWS_ACCESS_KEY_ID = "AKIA3K7SUOVXLDLWD5XZ"
    AWS_SECRET_ACCESS_KEY = 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
    # MAX_THROTTLING_ERROR_TOLERANCE = 10
